const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  LOAD_CHAT_MESSAGES_REQUEST: 'LOAD_CHAT_MESSAGES_REQUEST',
  LOAD_CHAT_MESSAGES_SUCCESS: 'LOAD_CHAT_MESSAGES_SUCCESS',
  LOAD_CHAT_MESSAGES_ERROR: 'LOAD_CHAT_MESSAGES_ERROR',

};

export default ACTION_TYPES;